package orga.takwa.ummati.entity.enums;

public enum NotificationType {
    WELCOME,
    EMAIL_VERIFIED,
    ONG_SUBMITTED,
    ONG_VALIDATED,
    ONG_REJECTED,
    MEMBERSHIP_REQUESTED,
    MEMBERSHIP_ACCEPTED,
    MEMBERSHIP_REJECTED,
    EVENT_PUBLISHED,
    EVENT_REMINDER_7D,
    EVENT_REMINDER_1D,
    EVENT_CANCELLED,
    EVENT_COMPLETED,
    SIGNUP_CONFIRMED,
    SIGNUP_WAITLISTED,
    SIGNUP_PROMOTED,
    FEEDBACK_REQUESTED,
    EVENT_ANNOUNCEMENT,
    GENERAL
}

